# Generated by Django 2.1.7 on 2019-04-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapi', '0002_auto_20190410_2110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Book',
        ),
    ]
